app:
  jwt:
    secret: heRJc1qDFrXxIzj1emY6m34z1blEJVhebRCofDAlZDMDEQFehWwTiSrrcpqBJODApaOHNYVGKRVuwhj4FKNURfHYxSvR0gqL
    duration: 30
spring:
  datasource:
    url: "jdbc:mysql://ee417.crxkzf89o3fh.eu-west-1.rds.amazonaws.com/EE417?useSSL=FALSE"
    username: "EE417"
    password: "2023_EE417"
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  sql:
    init:
      mode: always
      platform: mysql

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG