
# Create two types of roles
#INSERT INTO group_g_library.roles (id, name) VALUES (1, 'ADMIN');
#INSERT INTO group_g_library.roles (id, name) VALUES (2, 'USER');

# Create an admin user with password: secret (encoded in database)
#insert into group_g_library.members(id, username, email, password) values(1, 'admin', 'admin@gmail.com', '$2a$10$H/eRPpLQVaJTxH8Uod8lS..HaZpZ4XVmUcFouI68d4aSxuJLeV3JK');
# Create a regular user: tom.smith with password: secret (encoded in database)
#insert into group_g_library.members(id, username, email, firstname, surname, password) values(2, 'tom.smith', 'tom.smith@gmail.com', 'Tom', 'Smith', '$2a$10$H/eRPpLQVaJTxH8Uod8lS..HaZpZ4XVmUcFouI68d4aSxuJLeV3JK');

# Add roles to the accounts created
#insert into group_g_library.member_role(member_id,role_id) values (1,1);
#insert into group_g_library.member_role(member_id,role_id) values (2,2);

# Add 8 initial books to the library
#insert into group_g_library.books(id, isbn,title,author,publish_date,image_path,description)
#	values(1, 10001,'The DaVinci Code','Dan Brown','2003-03-18','images/daVinchiCode.jpg', 'While in Paris, Harvard symbologist Robert Langdon is awakened by a phone call in the dead of the night. The elderly curator of the Louvre has been murdered inside the museum, his body covered in baffling symbols. As Langdon and gifted French cryptologist Sophie Neveu sort through the bizarre riddles, they are stunned to discover a trail of clues hidden in the works of Leonardo da Vinci—clues visible for all to see and yet ingeniously disguised by the painter.');
#insert into group_g_library.books(id, isbn,title,author,publish_date,image_path,description)
#	values(2, 10002, 'Dubliners','James Joyce','2023-03-04','images/dubliners.jpg','This work of art reflects life in Ireland at the turn of the last century, and by rejecting euphemism, reveals to the Irish their unromantic realities. Each of the 15 stories offers glimpses into the lives of ordinary Dubliners, and collectively they paint a portrait of a nation.');
#insert into group_g_library.books(id,isbn,title,author,publish_date,image_path,description)
#	values(3, 11232,'The Firm','John Grisham','2023-02-23','images/theFirm.jpg','At the top of his class at Harvard Law, he had his choice of the best [law firms] in America. He made a deadly mistake. When Mitch McDeere signed on with Bendini, Lambert & Locke of Memphis, he thought he and his beautiful wife, Abby, were on their way. The firm leased him a BMW, paid off his school loans, arranged a mortgage and hired him a decorator. Mitch McDeere should have remembered what his brother Ray — doing fifteen years in a Tennessee jail — already knew. You never get nothing for nothing. Now the FBI has the lowdown on Mitch’s firm and needs his help. Mitch is caught between a rock and a hard place, with no choice — if he wants to live.');
#insert into group_g_library.books(id,isbn,title,author,publish_date,image_path,description)
#	values(4, 12345,'The Time Machine','H.G Wells','2023-03-10','images/theTimeMachine.jpg','So begins the Time Traveller’s astonishing firsthand account of his journey 800,000 years beyond his own era—and the story that launched H.G. Wells’s successful career and earned him his reputation as the father of science fiction. With a speculative leap that still fires the imagination, Wells sends his brave explorer to face a future burdened with our greatest hopes...and our darkest fears. A pull of the Time Machine’s lever propels him to the age of a slowly dying Earth. There he discovers two bizarre races—the ethereal Eloi and the subterranean Morlocks—who not only symbolize the duality of human nature, but offer a terrifying portrait of the men of tomorrow as well. Published in 1895, this masterpiece of invention captivated readers on the threshold of a new century. Thanks to Wells’s expert storytelling and provocative insight, The Time Machine will continue to enthrall readers for generations to come.');
#insert into group_g_library.books(id,isbn,title,author,publish_date,image_path,description)
#	values(5, 11111,'The Great Gatsby','Scott.F Fitzgerald','2023-01-07','images/theGreatGatsby.jpg','The Great Gatsby, F. Scott Fitzgeralds third book, stands as the supreme achievement of his career. This exemplary novel of the Jazz Age has been acclaimed by generations of readers. The story of the fabulously wealthy Jay Gatsby and his love for the beautiful Daisy Buchanan, of lavish parties on Long Island at a time when The New York Times noted "gin was the national drink and sex the national obsession," it is an exquisitely crafted tale of America in the 1920s.');
#insert into group_g_library.books(id,isbn,title,author,publish_date,image_path,description)
#	values(6, 43215,'Red Rabbit','Tom Clancy','2023-02-14','images/redRabbit.jpg','Long before he was President or head of the CIA, before he fought terrorist attacks on the Super Bowl or the White House, even before a submarine named Red October made its perilous way across the Atlantic, Jack Ryan was an historian, teacher, and recent ex-Marine temporarily living in England while researching a book. A series of deadly encounters with an IRA splinter group had brought him to the attention of the CIAs Deputy Director, Vice Admiral James Greer—as well as his counterpart with the British SIS, Sir Basil Charleston—and when Greer asked him if he wanted to come aboard as a freelance analyst, Jack was quick to accept. The opportunity was irresistible, and he was sure he could fit it in with the rest of his work.');
#insert into group_g_library.books(id,isbn,title,author,publish_date,image_path,description)
#	values(7, 22222,'A Tale Of Two Cities','Charles Dickens','2023-01-21','images/aTaleOfTwoCities.jpg','A Tale of Two Cities (1859) is a novel by Charles Dickens, set in London and Paris before and during the French Revolution. The novel depicts the plight of the French peasantry demoralized by the French aristocracy in the years leading up to the revolution, the corresponding brutality demonstrated by the revolutionaries toward the former aristocrats in the early years of the revolution, and many unflattering social parallels with life in London during the same period.');
#insert into group_g_library.books(id,isbn,title,author,publish_date,image_path,description)
#	values(8, 56784,'The Shining','Stephen King','2023-03-22','images/theShining.jpg','Jack Torrance's new job at the Overlook Hotel is the perfect chance for a fresh start. As the off-season caretaker at the atmospheric old hotel, he'll have plenty of time to spend reconnecting with his family and working on his writing. But as the harsh winter weather sets in, the idyllic location feels ever more remote...and more sinister. And the only one to notice the strange and terrible forces gathering around the Overlook is Danny Torrance, a uniquely gifted five-year-old.');
	
# Set two of the books (Dubliners and A Tale of Two cities) as checked out by member 2.
#insert into group_g_library.library_records(member_id,book_id,borrowed_date,due_date,is_returned) values (2, 2,'2023-03-04','2023-04-24',false);
#insert into group_g_library.library_records(member_id,book_id,borrowed_date,due_date,is_returned) values (2, 7,'2023-02-20','2023-03-20',false);
#insert into group_g_library.library_records(member_id,book_id,borrowed_date,due_date,is_returned) values (2, 3,'2023-01-20','2023-01-30',true);
